### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by GoogleCodeExporter** [qetzal/python-weather-api#21]
```
What steps will reproduce the problem?
1.does not work with urllib3
2.worked on older systems.
3.

What is the expected output? What do you see instead?
errors

What version of the product are you using? On what operating system?
debian wheezy

Please provide any additional information below.

```

Original issue reported on code.google.com by `eken...@gmail.com` on 4 Sep 2012 at 2:52

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Traceback (most recent call last):
  File "weather.py", line 1, in <module>
    import  pywapi
  File "/usr/local/lib/python2.7/dist-packages/pywapi.py", line 29, in <module>
    import urllib.request, urllib.error, urllib.parse
ImportError: No module named request

on Ubuntu 12.10
```

Original comment by `hdib...@gmail.com` on 29 Oct 2012 at 9:37

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r114.
```

Original comment by `jtas...@gmail.com` on 9 Mar 2013 at 2:18
- Changed state: **Fixed**
